### ISSUE TITLE
Font size helpers to use_extra_styles()

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#127]
```css
.fs10 { font-size:     6rem; }
.fs9  { font-size:     5rem; }
.fs8  { font-size:     4rem; }
.fs7  { font-size:     3rem; }
.fs6  { font-size:  2.25rem; }
.fs5  { font-size:   1.5rem; }
.fs4  { font-size:  1.25rem; }
.fs3  { font-size:     1rem; }
.fs2  { font-size: 0.875rem; }
.fs1  { font-size:  0.75rem; }
```
