### ISSUE TITLE
Source code language next to code boxes

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#147]
For [js4shiny](https://js4shiny.com), I built CSS styles that add the language name next to the code box. They're included in the (somewhat hidden) xaringan template in the [js4shiny R package](https://pkg.js4shiny.com) but the CSS for the code boxes specifically comes from https://github.com/gadenbuie/js4shiny/blob/main/inst/template-html/css/code.css

These styles (or something similar) could be moved in to xaringanExtra.

## Screenshots

![image](https://user-images.githubusercontent.com/5420529/144082293-1f11a6ce-66ab-458b-b2ee-79faaaf586ef.png)
![image](https://user-images.githubusercontent.com/5420529/144082397-92574b16-ff5f-491a-ac14-1642c140fbd0.png)
![image](https://user-images.githubusercontent.com/5420529/144082594-32f993cc-7ded-4015-84e6-b5820d89b1bb.png)

**Comment by jorgesinval** [comment]
I added:

```css
pre.stan,
...

pre.stan::after,
...

pre.stan {
  border-color: var(--red);
}

pre.stan::after {
  content: 'stan';
  color: var(--red);
}
```

But it did not work:

![image](https://user-images.githubusercontent.com/8278071/144683716-73d57c2a-0b6d-463f-b92a-8800cef68d29.png)

**Comment by gadenbuie** [comment]
oh no! I forgot an important component, which is the [JavaScript in this file](https://github.com/gadenbuie/js4shiny/blob/a70eab58bfa1661c96f40ab3b0a2f775aced4ee5/inst/rmarkdown/templates/js4shiny-xaringan/skeleton/assets/html/js4shiny-includes.html#L1-L39) that moves the source code class from the child `<code>` element to the `<pre>` parent element (too many flavors of markdown, amiright?). You'd also have to add `stan` to the [languages that get special treatment](https://github.com/gadenbuie/js4shiny/blob/a70eab58bfa1661c96f40ab3b0a2f775aced4ee5/inst/rmarkdown/templates/js4shiny-xaringan/skeleton/assets/html/js4shiny-includes.html#L5) (at the top of that script) and then include that whole thing in an `.html` file containing that `<script>` tag using the `includes: after_body` option ([here's an example](https://github.com/gadenbuie/js4shiny/blob/a70eab58bfa1661c96f40ab3b0a2f775aced4ee5/inst/rmarkdown/templates/js4shiny-xaringan/skeleton/skeleton.Rmd#L14-L15)).

Hope this helps!

**Comment by jorgesinval** [comment]
Thank you! I managed to add the `'stan'` reference to the `HTML file:

```HTML
    const langSpecial = ['r', 'stan', 'js', 'yaml', 'json', 'bash']
```

However, every time I change the `code.css` file in `~/js4shiny-main/inst/template-html/css/code.css`, adding:

```css

...

pre.stan {
  border-color: var(--blue);
}

pre.stan::after {
  content: 'stan';
  color: var(--blue);
}
...
pre.r,
pre.stan,
pre.js,
pre.md,
pre.markdown,
pre.yaml,
pre.json,
pre.bash,
pre.html,
pre.css {
  background: none;
}

pre.r::after,
pre.stan::after,
pre.js::after,
pre.md::after,
pre.markdown::after,
pre.yaml::after,
pre.json::after,
pre.bash::after,
pre.html::after,
pre.css::after {
  text-transform: uppercase;
  font-family: var(--font-header);
  left: -1.35em;
  bottom: -1.1em;
  transform-origin: top left;
  transform: rotate(-90deg);
}
```
But the result is the same:

![image](https://user-images.githubusercontent.com/8278071/144715448-9dc8de1c-89eb-4b71-ad34-43cc724975aa.png)

By the way, the file `code.css` in the directory `~/js4shiny-main/inst/rmarkdown/templates/js4shiny-xaringan/skeleton/assets/libs/js4shiny/css` is always rewritten to its previous version.

Any idea of what's happening? 

Thanks.


PS: I copied your repo I just tried to add some `stan` code to a new slide.
