### ISSUE TITLE
use_banner conflict with css border-top

### ISSUE THREAD

**Issue by jorgesinval** [gadenbuie/xaringanExtra#168]
The function `use_banner` does not place the top (right or left info) on the "true" top of the slide when using a custom `css` with the following code (i.e., border-top....):

```css
.remark-slide-content {
  background-color: #FAFAFA;
  border-top: 80px solid #c70831;
  font-size: 20px;
  font-weight: 300;
  line-height: 1.5;
  padding: 1em 2em 1em 2em
}
```

```r
xaringanExtra::use_banner(top_right = '<img src="https://pngimage.net/wp-content/uploads/2018/05/example-logo-png-1.png"  width="153"  alt="example">',
                          exclude = "title-slide")
```

![image](https://user-images.githubusercontent.com/8278071/173117571-ca2bd4de-51e9-4185-ab76-8ee5c1d747bc.png)

**Comment by gadenbuie** [comment]
The problem is that the large top border effectively means that the top of the slide content area is where the white and red meet. You can use negative margins on the top banner to move it back into place. Here's something that would work in your custom CSS:

```css
.xe-banner.top {
  margin-top: -60px;
}
```
