### ISSUE TITLE
Blurry slide content when using use_extra_styles(hover_code_line = TRUE)

### ISSUE THREAD

**Issue by mattwarkentin** [gadenbuie/xaringanExtra#32]
Hi @gadenbuie,

I was testing out the new `use_extra_styles()` features that were recently added to `{xaringanExtra}` and I noticed that for `xaringanExtra::use_extra_styles(hover_code_line = TRUE)` the entire slide becomes slightly blurry when hovering a code line. 

Is this expected behaviour? Not sure if this is just a me issue or if you have experienced this also.

**Comment by gadenbuie** [comment]
Hmmm, I haven't seen this. Can you take a screenshot? What browser are you using? And what version of xaringan are you using?

**Comment by mattwarkentin** [comment]
I am using `{xaringan}` 0.16

I made a screen recording of it. Hopefully you are able to view it. I had to zip it so GitHub would allow me to upload it.

[Screen Recording 2020-07-13 at 5.07.13 PM.zip](https://github.com/gadenbuie/xaringanExtra/files/4915129/Screen.Recording.2020-07-13.at.5.07.13.PM.zip)

**Comment by mattwarkentin** [comment]
Maybe it goes away when refreshing a slide...

**Comment by mattwarkentin** [comment]
When I flip to a slide the blurry effect occurs, but if I refresh it fixes for that slide, it seems.

**Comment by gadenbuie** [comment]
Okay, I see this too, it's a known issue with WebKit. I don't see the blurring on Chrome or Firefox, but it does occur for me on Safari.

I think the only way around this would be to do the animation in JavaScript and I'm not super excited about that idea, so I'm probably not going to fix it.

You can get the hover effect without the animation using this CSS

```css
/* Line Hover Indicator */
.remark-code-line:hover {
  font-weight: bold;
  opacity: 1 !important;
}

.remark-code-line:hover:before {
  content: "\25B6";
  color: #6d7e8a;
  position: absolute;
  transform: translateX(-22px);
}
```
