### ISSUE TITLE
[panelset] Set border none on panelset tab name links

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#60]
Looks bad in distill without this and should be done anyway.

```css
.panelset .panel-tabs .panel-tab > a {
	color: currentColor;
	text-decoration: none;
	border: none;
}
```
